language: node_js
node_js:
  - "node"

after_script:
  - gitbook build
  - grunt minify
  - mv ./tpm/_book/search_index.json ./dist/search_index.json
  - mv ./dist/tpm/_book/*.html ./dist/*.html
  - mv ./tmp/_book/gitbook/fonts ./dist/gitbooks/fonts
  - mv ./tmp/_book/gitbook/images ./dist/gitbooks/images
  - cd ./dist
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git add .
  - git commit -m "publish gitbook"
  - git push --force --quiet "https://${ACC_TOKEN}@${GH_REF}" master:${BRANCH}

branches:
  only:
    - master